name: first workflow
on:
    push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Welcome message 
          run: echo " hello Bhaii Jan"
        - name: List All files
          run: ls
        - name: Read File
          run: cat README.md